package org.sweetrazory.waystonesplus.memoryhandlers;

import org.sweetrazory.waystonesplus.WaystonesPlus;
import org.yaml.snakeyaml.Yaml;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Map;

public class LangManager {
    public static String versionWarning;
    public static String waystoneTypeNonexistent;
    public static String waystoneTypeMissing;
    public static String waystoneVisibilityMissing;
    public static String waystoneNameMissing;
    public static String noPermission;
    public static String reload;
    public static String notOwner;
    public static String wait;
    public static String newWaystoneName;
    public static String explorersMenuTitle;
    public static String selectorMenuTitle;
    public static String settingsMenuTitle;
    public static String iconMenuTitle;
    public static String typeMenuTitle;
    public static String teleportMenuTitle;
    public static String visibilityMenuTitle;
    public static String itemsMenuTitle;
    public static String prevPage;
    public static String nextPage;
    public static String returnText;
    public static String blocks;
    public static String particleMenuTitle;
    public static String blocksMenuTitle;
    public static String items;
    public static String noItemHeld;
    public static String newWaystoneTitle;
    public static String newWaystoneSubtitle;
    public static String invalidItem;
    public static String invalidVisibility;
    public static String adminListMenuTitle;
    public static String teleportTabAll;
    public static String teleportTabGlobal;
    public static String teleportTabOwned;
    public static String teleportTabExplored;
    public static String teleportTabFavorites;
    public static String teleportTabSelected;
    public static String teleportTabClick;
    public static String teleportTabShiftDefault;
    public static String teleportTabIsDefault;
    public static String teleportDefaultSet;
    public static String teleportFavorite;
    public static String teleportNotFavorite;
    public static String teleportFavoriteHint;
    public static String teleportFavoritedMessage;
    public static String teleportUnfavoritedMessage;
    public static String teleportInfoTitle;
    public static String teleportInfoName;
    public static String teleportInfoOwner;
    public static String teleportInfoVisibility;
    public static String teleportInfoWorld;
    public static String teleportInfoCoords;
    public static String resourcePackDisabled;
    public static String resourcePackUnavailable;
    public static String resourcePackAlreadyLoaded;
    public static String resourcePackSending;
    public static String resourcePackDeclinedReminder;
    public static String resourcePackDeclinedHowTo;

    public static void loadConfig() {
        File configFile = new File(WaystonesPlus.getInstance().getDataFolder().getAbsolutePath() + File.separator + "localization.yml");
        try (FileInputStream fis = new FileInputStream(configFile)) {
            Yaml yaml = new Yaml();
            Map<String, Object> config = yaml.load(fis);

            versionWarning = (String) config.getOrDefault("version-warning", "[ WaystonesPlus ] This plugin only supports 1.19.4 or higher versions!");
            waystoneTypeNonexistent = (String) config.getOrDefault("waystone-type-nonexistent", "A waystone variation with that name doesn't exist!");
            waystoneTypeMissing = (String) config.getOrDefault("waystone-type-missing", "You need to provide the Waystone type.");
            waystoneVisibilityMissing = (String) config.getOrDefault("waystone-visibility-missing", "You need to provide the Waystone visibility.");
            waystoneNameMissing = (String) config.getOrDefault("waystone-name-missing", "You need to provide the Waystone name.");
            noPermission = (String) config.getOrDefault("no-permission", "You don't have permissions to do that!");
            reload = (String) config.getOrDefault("reload", "&cReloading WaystonesPlus's config and waystones.");
            notOwner = (String) config.getOrDefault("not-owner", "&cYou are not the owner of this Waystone.");
            wait = (String) config.getOrDefault("wait", "&cPlease wait a moment...");
            newWaystoneName = (String) config.getOrDefault("new-waystone-name", "&7See /wsp help");
            explorersMenuTitle = (String) config.getOrDefault("explorers-menu-title", "&6Waystone Explorers Menu");
            selectorMenuTitle = (String) config.getOrDefault("selector-menu-title", "&6Waystone Option Selector");
            settingsMenuTitle = (String) config.getOrDefault("settings-menu-title", "&6Waystone Settings");
            iconMenuTitle = (String) config.getOrDefault("icon-menu-title", "&6Waystone Icon");
            typeMenuTitle = (String) config.getOrDefault("type-menu-title", "&6Waystone Type");
            teleportMenuTitle = (String) config.getOrDefault("teleport-menu-title", "&6Waystone Teleportation");
            visibilityMenuTitle = (String) config.getOrDefault("visibility-menu-title", "&6Waystone Visibility");
            itemsMenuTitle = (String) config.getOrDefault("items-menu-title", "&6Waystone Items");
            prevPage = (String) config.getOrDefault("prev-page", "&ePrevious Page");
            nextPage = (String) config.getOrDefault("next-page", "&eNext Page");
            returnText = (String) config.getOrDefault("return-text", "&eReturn");
            blocks = (String) config.getOrDefault("blocks", "&6Blocks");
            particleMenuTitle = (String) config.getOrDefault("particle-menu-title", "&6Waystone Particles");
            blocksMenuTitle = (String) config.getOrDefault("blocks-menu-title", "&6Blocks");
            items = (String) config.getOrDefault("items", "&6Items");
            noItemHeld = (String) config.getOrDefault("no-item-held", "&cYou are not holding an item.");
            invalidItem = (String) config.getOrDefault("invalid-item", "&cInvalid item. Please hold an item in your hand.");
            invalidVisibility = (String) config.getOrDefault("invalid-visibility", "&cInvalid visibility. Valid options: public, private.");
            adminListMenuTitle = (String) config.getOrDefault("admin-list-menu-title", "&6All Waystones (Admin)");
            newWaystoneTitle = (String) config.getOrDefault("new-waystone-title", "&8New Waystone:");
            newWaystoneSubtitle = (String) config.getOrDefault("new-waystone-subtitle", "&6%waystone_name%");
            teleportTabAll = (String) config.getOrDefault("teleport-tab-all", "&eAll");
            teleportTabGlobal = (String) config.getOrDefault("teleport-tab-global", "&eGlobal");
            teleportTabOwned = (String) config.getOrDefault("teleport-tab-owned", "&eMine");
            teleportTabExplored = (String) config.getOrDefault("teleport-tab-explored", "&eExplored");
            teleportTabFavorites = (String) config.getOrDefault("teleport-tab-favorites", "&eFavorites");
            teleportTabSelected = (String) config.getOrDefault("teleport-tab-selected", "&aCurrently viewing");
            teleportTabClick = (String) config.getOrDefault("teleport-tab-click", "&7Click to open this category");
            teleportTabShiftDefault = (String) config.getOrDefault("teleport-tab-shift-default", "&7Shift-click to set as default");
            teleportTabIsDefault = (String) config.getOrDefault("teleport-tab-is-default", "&6★ Default category");
            teleportDefaultSet = (String) config.getOrDefault("teleport-default-set", "&aDefault teleport category set to &e%filter%&a.");
            teleportFavorite = (String) config.getOrDefault("teleport-favorite", "&6★ Favorited");
            teleportNotFavorite = (String) config.getOrDefault("teleport-not-favorite", "&7Not favorited");
            teleportFavoriteHint = (String) config.getOrDefault("teleport-favorite-hint", "&7Shift-click to favorite / unfavorite");
            teleportFavoritedMessage = (String) config.getOrDefault("teleport-favorited-message", "&aFavorited &e%waystone%&a.");
            teleportUnfavoritedMessage = (String) config.getOrDefault("teleport-unfavorited-message", "&7Unfavorited &e%waystone%&7.");
            teleportInfoTitle = (String) config.getOrDefault("teleport-info-title", "&6Waystone Info");
            teleportInfoName = (String) config.getOrDefault("teleport-info-name", "&7Name: &f%name%");
            teleportInfoOwner = (String) config.getOrDefault("teleport-info-owner", "&7Owner: &f%owner%");
            teleportInfoVisibility = (String) config.getOrDefault("teleport-info-visibility", "&7Visibility: &f%visibility%");
            teleportInfoWorld = (String) config.getOrDefault("teleport-info-world", "&7World: &f%world%");
            teleportInfoCoords = (String) config.getOrDefault("teleport-info-coords", "&7Location: &f%x%, %y%, %z%");
            resourcePackDisabled = (String) config.getOrDefault("resource-pack-disabled", "&cThe WaystonesPlus resource pack is disabled on this server.");
            resourcePackUnavailable = (String) config.getOrDefault("resource-pack-unavailable", "&cThe resource pack is not available right now. Try again later.");
            resourcePackAlreadyLoaded = (String) config.getOrDefault("resource-pack-already-loaded", "&aYou already have the WaystonesPlus menu icons loaded.");
            resourcePackSending = (String) config.getOrDefault("resource-pack-sending", "&eRe-sending the WaystonesPlus menu icon pack — accept the prompt when it appears.");
            resourcePackDeclinedReminder = (String) config.getOrDefault("resource-pack-declined-reminder", "&7You declined WaystonesPlus menu icons. Run &e/wsp pack &7anytime to try again.");
            resourcePackDeclinedHowTo = (String) config.getOrDefault("resource-pack-declined-how-to", "&7If you get no prompt: Multiplayer → select this server → &eEdit &7→ set &eServer Resource Packs &7to &ePrompt &7or &eEnabled&7.");
        } catch (FileNotFoundException e) {
            throw new RuntimeException(e);
        } catch (IOException e) {
            WaystonesPlus.Logger().severe("Error reading localization.yml file:");
            e.printStackTrace();
            throw new RuntimeException(e);
        }
    }
}
